"use client";
import Link from "next/link";
import { useState } from "react";
import { analyzeText, type Template } from "@/lib/workspace/model";
import { useWorkspace } from "@/lib/workspace/store";
import { requestAI } from "@/lib/workspace/ai-client";
import { WorkspacePage, Empty, Message, useAIStatus, AIHint, ws } from "./WorkspaceUI";
type Analysis=Pick<Template,"headings"|"style"|"summary">;
export default function TemplatesPage(){
  const {data,error,blocked,save}=useWorkspace();const available=useAIStatus();const [name,setName]=useState("");const [text,setText]=useState("");const [analysis,setAnalysis]=useState<Analysis|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [problem,setProblem]=useState("");
  async function upload(file?:File){if(!file)return;setBusy(true);setProblem("");setMessage("");setAnalysis(null);try{const form=new FormData();form.append("file",file);const response=await fetch("/api/templates/extract",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);setName(result.name);setText(result.text);setAnalysis(result);}catch(e){setProblem(e instanceof Error?e.message:"업로드에 실패했어요.");}finally{setBusy(false);}}
  async function analyze(){if(text.trim().length<10){setProblem("분석할 양식 내용을 10자 이상 입력해주세요.");return;}setBusy(true);setProblem("");try{setAnalysis(available?await requestAI<Analysis>("template",{text}):analyzeText(text));}catch(e){setProblem(e instanceof Error?e.message:"분석에 실패했어요.");}finally{setBusy(false);}}
  function store(){if(!analysis||!name.trim())return;const template:Template={id:crypto.randomUUID(),name:name.trim(),text,...analysis,createdAt:new Date().toISOString()};if(save(prev=>({...prev,templates:[template,...prev.templates]}))){setMessage("우리 원 양식으로 저장했어요. 계획안 생성 화면에서 선택할 수 있어요.");setName("");setText("");setAnalysis(null);}}
  return <WorkspacePage title="원 양식 분석" description="익숙한 기관 양식을 읽고, 우리 원의 문서 작성 방식을 이어갑니다."><section className={ws.hero}><div><div className={ws.eyebrow}>TEMPLATE · 우리 원의 방식 그대로</div><h2>쓰던 양식을 올리면,<br/>작성의 기준이 생겨요.</h2><p>항목 순서와 문체, 담아야 할 내용을 확인하고 계획안 생성에 활용하세요.</p></div><span className={ws.heroIcon}>▤</span></section><Message error>{error||problem}</Message><Message>{message}</Message><div className={ws.equalGrid}><section className={ws.card}><h2>기존 양식 불러오기</h2><AIHint available={available}/><div className={ws.upload}><span className={ws.count}>↑</span><h3>기관에서 사용하는 문서를 선택해주세요</h3><p className={ws.muted}>PDF · DOCX · TXT · MD · CSV / 최대 5MB</p><input aria-label="기관 양식 파일" disabled={busy} type="file" accept=".pdf,.docx,.txt,.md,.csv" onChange={e=>{void upload(e.target.files?.[0]);e.target.value="";}}/></div><p className={ws.hint}>HWP/HWPX는 PDF·DOCX로 변환해주세요. 스캔 이미지의 문자 인식과 원본 표 배치 복제는 지원하지 않습니다.</p><div className={ws.form}><label className={ws.field}>양식 이름<input disabled={busy} maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="양식 이름을 입력해주세요"/></label><label className={ws.field}>추출 내용 / 직접 붙여넣기<textarea disabled={busy} maxLength={60000} value={text} onChange={e=>{setText(e.target.value);setAnalysis(null);}} placeholder="기존 양식의 내용을 붙여넣어도 분석할 수 있어요."/></label><button className={ws.primary} disabled={busy||!text.trim()} onClick={analyze}>{busy?"문서를 읽고 있어요…":available?"AI로 구조·성향 분석":"문서 구조 분석"}</button></div></section><section className={ws.card}><h2>양식 분석 결과</h2>{busy?<div className={ws.loading}><span>🌱</span><p>문서의 항목과 작성 방식을 살펴보고 있어요.</p></div>:analysis?<><span className={ws.badge}>{analysis.style}</span><p style={{margin:"16px 0"}}>{analysis.summary}</p><label className={ws.field}>사용할 항목 · 한 줄에 하나씩<textarea value={analysis.headings.join("\n")} onChange={e=>setAnalysis({...analysis,headings:e.target.value.split("\n").filter(Boolean).slice(0,20)})}/></label><p className={ws.hint}>텍스트에서 추출한 항목 후보입니다. 제목·순서를 검토한 뒤 저장해주세요.</p><div className={ws.actions}><button className={ws.primary} disabled={!name.trim()||!analysis.headings.length||blocked} onClick={store}>우리 원 양식으로 저장</button></div></>:<Empty title="우리 원 양식을 기다리고 있어요">문서를 올리거나 양식 내용을 붙여넣어주세요.</Empty>}</section></div><div className={ws.between} style={{margin:"28px 0 15px"}}><h2>저장한 기관 양식 {data.templates.length}</h2><Link href="/plans/annual/new" className={ws.link}>계획안에 적용하기 →</Link></div><div className={ws.cards}>{data.templates.map(t=><article key={t.id} className={ws.card}><span className={ws.badge}>{t.style}</span><h3 style={{marginTop:14}}>{t.name}</h3><p className={ws.muted}>{t.headings.join(" · ")}</p><details style={{marginTop:14}}><summary className={ws.link}>원문 확인</summary><div className={ws.preview}>{t.text}</div></details><Link href={`/plans/annual/new?template=${encodeURIComponent(t.id)}`} className={ws.primary} style={{marginTop:18}}>이 양식으로 계획안 작성</Link></article>)}</div></WorkspacePage>;
}
