"""observations class_id date index

Revision ID: ab4784c999ea
Revises: 1eae36a7c951
Create Date: 2026-09-29 20:39:44.119695

관찰 기록 목록이 반 + 기간으로 거른다 (docs/api-spec.md 「DB 에 아직 없는 것」 INDEX(class_id, date)).
class_id 단일 인덱스는 복합 인덱스의 앞 칸이 대신하므로 뺀다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4784c999ea'
down_revision: Union[str, None] = '1eae36a7c951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_class_id'), table_name='observations')
    op.create_index('ix_observations_class_id_date', 'observations', ['class_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_class_id_date', table_name='observations')
    op.create_index(op.f('ix_observations_class_id'), 'observations', ['class_id'], unique=False)
    # ### end Alembic commands ###
