"""add forms table

Revision ID: 5d6cce1120fa
Revises: 1eae36a7c951
Create Date: 2026-09-29 15:18:07.882651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d6cce1120fa'
down_revision: Union[str, None] = '1eae36a7c951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='화면에 보일 이름. 지금은 filename 과 같다 (ADR-020 결정 3)'),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='표 → 행 → 셀 {text, rowspan, colspan}'),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='라벨 → 표준 키 또는 null (ADR-009)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_forms_center_id_centers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms'))
    )
    op.create_index(op.f('ix_forms_center_id'), 'forms', ['center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_center_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
