"""routine records and routine document source

일과 기록 테이블(§10-1, ADR-025)과, 일일 보육일지가 그것을 근거로 쓰도록
document_sources.source_kind 에 'routine' 을 더한다. CHECK 변경은 autogenerate 가 못 잡아 손으로 적었다.

Revision ID: 2652c5dee127
Revises: d2a8f06b3e91
Create Date: 2026-10-06 19:50:14.299353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2652c5dee127'
down_revision: Union[str, None] = 'a39829cde4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False, comment='하루 안에서 표시 순서. 같으면 시작 시간 · id 순이다'),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False, comment='일과 이름 — 「오전 실내놀이」. 원마다 달라 교사가 적는다'),
    sa.Column('plan', sa.Text(), server_default='', nullable=False, comment='활동계획'),
    sa.Column('execution', sa.Text(), server_default='', nullable=False, comment='활동실행 — 사실 층이다. 교사가 쓰고 AI 가 쓰지 않는다'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_routine_records_name_not_blank')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_routine_records_position_not_negative')),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR start_time < end_time', name=op.f('ck_routine_records_time_range')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_routine_records_class_id_classes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_records'))
    )
    op.create_index('ix_routine_records_class_id_date', 'routine_records', ['class_id', 'date'], unique=False)
    # ### end Alembic commands ###
    op.drop_constraint(op.f('ck_document_sources_source_kind'), 'document_sources', type_='check')
    op.create_check_constraint(
        'source_kind', 'document_sources', "source_kind IN ('observation', 'document', 'routine')"
    )


def downgrade() -> None:
    # 일과 기록을 근거로 쓴 사본이 남아 있으면 옛 CHECK 를 다시 걸 수 없다. 그 사본부터 지운다.
    op.execute("DELETE FROM document_sources WHERE source_kind = 'routine'")
    op.drop_constraint(op.f('ck_document_sources_source_kind'), 'document_sources', type_='check')
    op.create_check_constraint(
        'source_kind', 'document_sources', "source_kind IN ('observation', 'document')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_routine_records_class_id_date', table_name='routine_records')
    op.drop_table('routine_records')
    # ### end Alembic commands ###
