"""initial schema

Revision ID: 91f8d595e285
Revises: 
Create Date: 2026-09-11 00:29:57.846851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91f8d595e285'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False, comment='불변 슬러그. YAML 최상위 키. 한 번 정하면 고치지 않는다'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False, comment='학년도 기준 연 나이(3·4·5). 만 나이 아님'),
    sa.Column('age_max', sa.Integer(), nullable=False, comment='학년도 기준 연 나이(3·4·5). 만 나이 아님'),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='resources/rules/safety_flags.yaml 의 값. 선별 3순위'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='5영역 태그·주제 태그. ADR-001:19'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age_max BETWEEN 3 AND 5', name=op.f('ck_activities_age_max_range')),
    sa.CheckConstraint('age_min <= age_max', name=op.f('ck_activities_age_range')),
    sa.CheckConstraint('age_min BETWEEN 3 AND 5', name=op.f('ck_activities_age_min_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('code', name=op.f('uq_activities_code'))
    )
    op.create_index('ix_activities_tags', 'activities', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='원 이름'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centers'))
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='반 이름'),
    sa.Column('age_min', sa.Integer(), nullable=False, comment='반 최저 연령. 학년도 기준 연 나이'),
    sa.Column('age_max', sa.Integer(), nullable=False, comment='단일 연령반은 age_min 과 같은 값'),
    sa.Column('teacher_id', sa.Integer(), nullable=True, comment='담임. users.id 예정. FK 와 인덱스는 인증 PR(8주차)에서'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age_max BETWEEN 3 AND 5', name=op.f('ck_classes_age_max_range')),
    sa.CheckConstraint('age_min <= age_max', name=op.f('ck_classes_age_range')),
    sa.CheckConstraint('age_min BETWEEN 3 AND 5', name=op.f('ck_classes_age_min_range')),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_classes_center_id_centers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('center_id', 'name', name=op.f('uq_classes_center_id_name'))
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='평문 실명. ADR-004'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_children_class_id_classes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    op.create_index(op.f('ix_children_class_id'), 'children', ['class_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_children_class_id'), table_name='children')
    op.drop_table('children')
    op.drop_table('classes')
    op.drop_table('centers')
    op.drop_index('ix_activities_tags', table_name='activities', postgresql_using='gin')
    op.drop_table('activities')
    # ### end Alembic commands ###
