"""add template profiles

월간 TemplateProfile 버전 행과 원 기본 · 반 override 포인터 (Contract 2, 결정 문서 C2.8).
포인터는 복합 FK 로 같은 원 · 같은 문서 종류의 존재하는 버전만 가리킨다. 기존 테이블은 건드리지 않는다.

Revision ID: 6eab3767534d
Revises: 2652c5dee127
Create Date: 2026-10-08 09:37:04.463330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eab3767534d'
down_revision: Union[str, None] = '2652c5dee127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False, comment='소유 원. body 의 institution_ref 와 같다'),
    sa.Column('doc_kind', sa.String(length=10), nullable=False, comment='monthly'),
    sa.Column('profile_id', sa.String(length=64), nullable=False, comment='Profile 계열. 한 원에 속한다. body 의 profile_ref 와 같다'),
    sa.Column('profile_version', sa.String(length=20), nullable=False, comment='v1, v2, ...'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='DRAFT(편집 중) | READY(불변) | ARCHIVED(목록에서 숨김)'),
    sa.Column('parent_version', sa.String(length=20), nullable=True, comment='이 DRAFT 를 파생시킨 READY 버전. Reference 기반 시작은 null'),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Core TemplateProfile 전체. 이것이 원본이고 위 칸들은 여기서 유도한다'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='이 버전을 만든 계정'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_kind IN ('monthly')", name=op.f('ck_template_profiles_doc_kind')),
    sa.CheckConstraint("status IN ('DRAFT','READY','ARCHIVED')", name=op.f('ck_template_profiles_status')),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_template_profiles_center_id_centers')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_template_profiles_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_profiles')),
    sa.UniqueConstraint('center_id', 'doc_kind', 'profile_id', 'profile_version', name='uq_template_profiles_owner_ref'),
    sa.UniqueConstraint('profile_id', 'profile_version', name=op.f('uq_template_profiles_profile_id_profile_version'))
    )
    op.create_index(op.f('ix_template_profiles_center_id'), 'template_profiles', ['center_id'], unique=False)
    op.create_table('template_profile_defaults',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('doc_kind', sa.String(length=10), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False, comment='마지막으로 바꾼 계정'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id', 'doc_kind', 'profile_id', 'profile_version'], ['template_profiles.center_id', 'template_profiles.doc_kind', 'template_profiles.profile_id', 'template_profiles.profile_version'], name='fk_template_profile_defaults_target'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_template_profile_defaults_center_id_centers')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_template_profile_defaults_changed_by_users')),
    sa.PrimaryKeyConstraint('center_id', 'doc_kind', name=op.f('pk_template_profile_defaults'))
    )
    op.create_table('template_profile_overrides',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('doc_kind', sa.String(length=10), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False, comment='반의 원. 대상 Profile 도 이 원 것이어야 한다'),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False, comment='마지막으로 바꾼 계정'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id', 'doc_kind', 'profile_id', 'profile_version'], ['template_profiles.center_id', 'template_profiles.doc_kind', 'template_profiles.profile_id', 'template_profiles.profile_version'], name='fk_template_profile_overrides_target'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_template_profile_overrides_center_id_centers')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_template_profile_overrides_changed_by_users')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_template_profile_overrides_class_id_classes')),
    sa.PrimaryKeyConstraint('class_id', 'doc_kind', name=op.f('pk_template_profile_overrides'))
    )
    op.create_index(op.f('ix_template_profile_overrides_center_id'), 'template_profile_overrides', ['center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_profile_overrides_center_id'), table_name='template_profile_overrides')
    op.drop_table('template_profile_overrides')
    op.drop_table('template_profile_defaults')
    op.drop_index(op.f('ix_template_profiles_center_id'), table_name='template_profiles')
    op.drop_table('template_profiles')
    # ### end Alembic commands ###
