"""documents status comment unconfirm

Revision ID: 0340d141da97
Revises: ab4784c999ea
Create Date: 2026-09-30 11:44:07.758234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0340d141da97'
down_revision: Union[str, None] = 'ab4784c999ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='DRAFT <-> CONFIRMED. 되돌리기는 unconfirm (§11)',
               existing_comment='DRAFT -> CONFIRMED. 한 방향이다. 되돌리기는 P1',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='DRAFT -> CONFIRMED. 한 방향이다. 되돌리기는 P1',
               existing_comment='DRAFT <-> CONFIRMED. 되돌리기는 unconfirm (§11)',
               existing_nullable=False)
    # ### end Alembic commands ###
