"""add consent_confirmed_at, children code, split center region

Revision ID: 52bd3f0c6560
Revises: b38df879442b
Create Date: 2026-09-21 14:52:48.117846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bd3f0c6560'
down_revision: Union[str, None] = 'b38df879442b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('region_sido', sa.String(length=30), nullable=False, comment='시·도. 화면이 2단으로 받는다 (docs/PRD.md S1)'))
    op.add_column('centers', sa.Column('region_sigungu', sa.String(length=30), nullable=False, comment='시·군·구. 지역사회 연계 활동 선별에 쓴다'))
    op.drop_column('centers', 'region')
    op.add_column('children', sa.Column('code', sa.String(length=20), nullable=False, comment='LLM 에 나가는 가명. 받침 있는 더미 한글 이름 (ADR-004). 반 안에서 유일하다'))
    op.create_unique_constraint('uq_children_class_id_code', 'children', ['class_id', 'code'])
    op.add_column('classes', sa.Column('consent_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='동의 확인 시각. 아동 0명이면 아동 수로 복원할 수 없다 (docs/PRD.md S2)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'consent_confirmed_at')
    op.drop_constraint('uq_children_class_id_code', 'children', type_='unique')
    op.drop_column('children', 'code')
    op.add_column('centers', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='시·도 + 시·군·구. 지역사회 연계 활동 선별에 쓴다 (docs/PRD.md S1)'))
    op.drop_column('centers', 'region_sigungu')
    op.drop_column('centers', 'region_sido')
    # ### end Alembic commands ###
