"""add plans table

Revision ID: 1eae36a7c951
Revises: f903a45ea894
Create Date: 2026-09-29 10:51:01.216788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eae36a7c951'
down_revision: Union[str, None] = 'f903a45ea894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_ref', sa.String(length=64), nullable=False, comment='p0-planning 의 PlanId. body 안의 값과 같다'),
    sa.Column('center_id', sa.Integer(), nullable=False, comment='원 격리용. 조회가 항상 이 값으로 먼저 걸린다'),
    sa.Column('kind', sa.String(length=10), nullable=False, comment='annual | monthly'),
    sa.Column('school_year', sa.Integer(), nullable=False, comment='학년도. 3월~익년 2월'),
    sa.Column('classroom_ref', sa.String(length=50), nullable=False, comment='도메인이 쓰는 반 참조. classes.id 를 문자열로 담는다'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='DRAFT | CONFIRMED. body 의 status 에서 꺼낸 값이다'),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='도메인 객체 전체. 이것이 원본이고 위 칸들은 여기서 유도한다'),
    sa.Column('sub_themes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='월 -> 소주제 배열. {"3": ["..."]}'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='확정 시각. body 의 감사 기록에서 꺼낸 값이다 — 목록이 12개월치를 매번 되돌리지 않게 한다'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('annual','monthly')", name=op.f('ck_plans_kind')),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED')", name=op.f('ck_plans_status')),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_plans_center_id_centers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('plan_ref', name=op.f('uq_plans_plan_ref'))
    )
    op.create_index(op.f('ix_plans_center_id'), 'plans', ['center_id'], unique=False)
    op.create_index(op.f('ix_plans_classroom_ref'), 'plans', ['classroom_ref'], unique=False)
    op.create_index(op.f('ix_plans_plan_ref'), 'plans', ['plan_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_plan_ref'), table_name='plans')
    op.drop_index(op.f('ix_plans_classroom_ref'), table_name='plans')
    op.drop_index(op.f('ix_plans_center_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
