"""add center_invites

같은 원의 다른 교사를 들이는 1회용 초대 코드 (api-spec.md §1-1 · ADR-029).

Revision ID: d7c6da04c909
Revises: 2652c5dee127
Create Date: 2026-10-10 09:08:08.907688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c6da04c909'
down_revision: Union[str, None] = '2652c5dee127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='secrets 로 만든 10자. 추측할 수 없다'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='코드를 만든 교사'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True, comment='코드로 들어온 교사. 쓰기 전에는 NULL'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_center_invites_center_id_centers')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_center_invites_created_by_users')),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name=op.f('fk_center_invites_used_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_center_invites_code'))
    )
    op.create_index(op.f('ix_center_invites_center_id'), 'center_invites', ['center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_invites_center_id'), table_name='center_invites')
    op.drop_table('center_invites')
    # ### end Alembic commands ###
