"""add center director_name region, class teacher_name child_count

Revision ID: b38df879442b
Revises: 979d1991638a
Create Date: 2026-09-16 08:45:24.996843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38df879442b'
down_revision: Union[str, None] = '979d1991638a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('director_name', sa.String(length=50), nullable=False, comment='결재란 「원장」. 계획안에 인쇄된다 (docs/PRD.md S1)'))
    op.add_column('centers', sa.Column('region', sa.String(length=50), nullable=False, comment='시·도 + 시·군·구. 지역사회 연계 활동 선별에 쓴다 (docs/PRD.md S1)'))
    op.add_column('classes', sa.Column('teacher_name', sa.String(length=50), nullable=False, comment='담임 이름. 계획안에 인쇄된다. teacher_id 와 다르다 (ADR-010 결과)'))
    op.add_column('classes', sa.Column('child_count', sa.Integer(), nullable=True, comment='현재 원아 수. 선택. 아동 명단 입력 진행률에 쓴다 (docs/PRD.md S2)'))
    op.alter_column('classes', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment='담임 계정. users.id 예정. FK 와 인덱스는 인증 PR(8주차)에서',
               existing_comment='담임. users.id 예정. FK 와 인덱스는 인증 PR(8주차)에서',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'teacher_id',
               existing_type=sa.INTEGER(),
               comment='담임. users.id 예정. FK 와 인덱스는 인증 PR(8주차)에서',
               existing_comment='담임 계정. users.id 예정. FK 와 인덱스는 인증 PR(8주차)에서',
               existing_nullable=True)
    op.drop_column('classes', 'child_count')
    op.drop_column('classes', 'teacher_name')
    op.drop_column('centers', 'region')
    op.drop_column('centers', 'director_name')
    # ### end Alembic commands ###
